package com.bkper.billing.google;

public enum GCPEventType {

    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    ENTITLEMENT_PLAN_CHANGE,
    ENTITLEMENT_CREATION_REQUESTED,
    ENTITLEMENT_ACTIVATION_REQUESTED,
    ENTITLEMENT_PLAN_CHANGE_REQUESTED,
    ENTITLEMENT_PLAN_CHANGED,
    ENTITLEMENT_PENDING_CANCELLATION,
    ENTITLEMENT_ACTIVE,
    ENTITLEMENT_CANCELLED,
    ENTITLEMENT_SUSPENDED,
    ENTITLEMENT_DELETED,
}
